const localization = {
  en: {
    dashboard: 'Dashboard',
    exam_date: 'Exam date',
    class_room: 'Class Room',
    notice_board: 'Notice Board',
    messages: 'Messages',
    results: 'Results',
    notification: 'Notification',
    settings: 'Settings',
    theme: 'Theme',
    language: 'Language',
    search: 'Search',
    total_students: 'Total Students',
    online_activate: 'Online Activate',
    online_learning: 'Online learning',
    attendantness: 'Attendantness',
    activate_users: 'Activate Users',
    online_study: 'Online Study',
    class_statistics: 'Class Statistics',
    exam_schedule: 'Exam Schedule',
    today_incomeing_classes: 'Today Incomeing Classes',
    joined: 'joined',
    join_now: 'Join Now',
    all_events: 'All Events',
  },
  uk: {
    dashboard: 'Панель',
    exam_date: 'Дата іспиту',
    class_room: 'Класна кімната',
    notice_board: 'Дошка оголошень',
    messages: 'Повідомлення',
    results: 'Результати',
    notification: "Пам'ятка",
    settings: 'Налаштування',
    theme: 'Тема',
    language: 'Мова',
    search: 'Пошук',
    total_students: 'Всього студентів',
    online_activate: 'Активних',
    online_learning: 'Онлайн навчання',
    attendantness: 'Обслуговування',
    activate_users: 'Активних користувачів',
    online_study: 'Онлайн навчання',
    class_statistics: 'Статистика класу',
    exam_schedule: 'Розклад іспитів',
    today_incomeing_classes: 'Сьогодні вхідні заняття',
    joined: 'приєднався',
    join_now: 'Приєднатися',
    all_events: 'Усі події',
  },
};

export default localization;
